# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        python -m nltk.downloader punkt stopwords
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 data/clean/*.py --count --select=E9,F63,F7,F82 --show-source --statistics
    - name: Test processed data with pytest and doctest
      run: |
        pytest --doctest-modules data/processed/*jenny_w_doc.py
        pytest --doctest-modules data/processed/*wenhao_w_doc.py
    # - name: Test processed data with pytest and no doctest
    #   run: |
    #     pytest data/processed/*_wo_doc.py
